ProcedureDLL  md5_cv(*test, *result)
  temp.s  = PeekS(*test)
  password.s  = UCase(MD5Fingerprint(@temp, StringByteLength(temp)))
  password  = Right(password, 16);
  PokeS(*result, password)
EndProcedure

;
; PureBUILD Build = 3 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.50 (Windows - x86)
; ExecutableFormat = Shared Dll
; CursorPosition = 3
; Folding = -
; EnableXP
; Executable = I:\VC++6_cv\cvPXISDK\cvPXIRunTime\¸¨Öú\cvPXIRunTimeSN\Release\md5_cv.dll
; EnableCompileCount = 3
; EnableBuildCount = 3
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT