IncludePath "BIN"

current.s = GetCurrentDirectory()

path.s = current + "bin"

If  FindString(GetEnvironmentVariable("PATH"), "doxygen", 1)
  ;
Else
  parameter.s ="PATH " + Chr(34) + GetEnvironmentVariable("PATH") + ";" + path + Chr(34)
EndIf  
  
temp_folder.s = GetTemporaryDirectory()

file1_name.s  = temp_folder + "setx.exe"

result.q = FileSize(file1_name)
If  result > 0
  ;
Else
  file1 = CreateFile(#PB_Any, file1_name)
  WriteData(file1, ?filestart1, ?fileend1 - ?filestart1)
  CloseFile(file1)
EndIf   

result = RunProgram(file1_name, parameter, temp_folder, #PB_Program_Wait | #PB_Program_Hide)


If  result
  MessageBox_(GetFocus_(), "set ok!" + Chr(10)  + parameter, "..cv..", #MB_OK | #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
Else
  MessageBox_(GetFocus_(), "error!", "..cv..", #MB_OK | #MB_ICONERROR|#MB_SYSTEMMODAL)
EndIf

DeleteFile(file1_name)


End



DataSection
    
  filestart1: 
    IncludeBinary "setx.exe" 
  fileend1:     
  
EndDataSection



;
; PureBUILD Build = 29 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 29
; EnableXP
; Executable = ..\doxygen_env_refresh.exe
; CompileSourceDirectory
; EnableCompileCount = 52
; EnableBuildCount = 26
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv