
  WSysName.s = Space(255)
  GetSystemDirectory_(WSysName, @Null)

  hwnd  = OpenWindow(#PB_Any, 0, 0, 231, 173, "扩展名助手_cv_2012",  #PB_Window_MinimizeGadget | #PB_Window_SystemMenu | #PB_Window_SizeGadget | #PB_Window_TitleBar | #PB_Window_ScreenCentered)
  button_modified = ButtonGadget(#PB_Any, 10, 140, 50, 20, "更改", #PB_Button_Default)
  button_browser =  ButtonGadget(#PB_Any, 10, 40, 50, 20, "浏览")
  combo_extlist = ComboBoxGadget(#PB_Any, 10, 10, 200, 20)
  string  = StringGadget(#PB_Any, 10, 70, 210, 60, "要使用打开的程序路径", #ES_MULTILINE | #ESB_DISABLE_LEFT | #ESB_DISABLE_RIGHT | #ES_AUTOVSCROLL | #WS_VSCROLL)
  
  file1 = ReadFile(#PB_Any, "ext_list.txt");
  If file1                 ; if the file could be read, we continue...
    While Eof(file1) = 0           ; loop as long the 'end of file' isn't reached
      AddGadgetItem(combo_extlist, -1, ReadString(file1)) 
    Wend
    CloseFile(file1)               ; close the previously opened file
  Else
    MessageBox_(#Null, "no ext_list.txt!", "cv", #MB_OK | #MB_ICONERROR)
  EndIf
  SetGadgetState(combo_extlist, 0)     

  
  DisableGadget(button_modified, 1)
      
  
  
  Repeat
    Event.l = WaitWindowEvent()
    Select  Event
      ;===========================
      Case  #PB_Event_Menu
        Select EventMenu()
          Case  0
          Case  1
        EndSelect
      ;===========================
      Case  #PB_Event_Gadget
        Select  EventGadget()
          Case  button_browser
            Pattern$ = "可执行文件 (*.exe)|*.exe|All files (*.*)|*.*"
            Pattern = 0    ; use the first of the three possible patterns as standard
            file2.s = OpenFileRequester("Please choose file to open", "", Pattern$, Pattern)
            If  file2 = ""
              MessageBox_(#Null, "please choose one file!", "cv", #MB_OK | #MB_ICONINFORMATION)
              DisableGadget(button_modified, 1)
            Else
              DisableGadget(button_modified, 0)
            EndIf
            SetGadgetText(string, file2)
          Case  button_modified
            ext_name.s  = StringField(StringField(GetGadgetText(combo_extlist), 1, "|"), 2, ".")
            parameter.s = "/c assoc ." + ext_name + "=" + ext_name + "file"
            ;result = RunProgram(WSysName+"\cmd.exe", parameter, WSysName, #PB_Program_Wait)
            ShellExecute_(#Null, #Null, WSysName+"\cmd.exe", parameter, WSysName, #SW_HIDE)
            parameter = "/c ftype " + ext_name + "file=" + GetGadgetText(string) + " %1"
            ;result = RunProgram(WSysName+"\cmd.exe", parameter, WSysName, #PB_Program_Wait) 
            ShellExecute_(#Null, #Null, WSysName+"\cmd.exe", parameter, WSysName, #SW_HIDE)
            MessageBox_(#Null, "Set OK!", "cv", #MB_OK | #MB_ICONINFORMATION)
        EndSelect
    EndSelect
  Until Event = #PB_Event_CloseWindow Or  quit  = #True       
  
  



;
; PureBUILD Build = 7 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.50 (Windows - x86)
; CursorPosition = 8
; EnableXP
; UseIcon = Pizza.ico
; Executable = Release\ext_assoc.exe
; EnableCompileCount = 49
; EnableBuildCount = 7
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv