;read a key from the registry
Procedure.s ReadRegKey(OpenKey.l, SubKey.s, ValueName.s)
    hKey.l = 0
    KeyValue.s = Space(255)
    Datasize.l = 255
    If RegOpenKeyEx_(OpenKey, SubKey, 0, #KEY_READ, @hKey)
        KeyValue = "Error Opening Key"
    Else
        If RegQueryValueEx_(hKey, ValueName, 0, 0, @KeyValue, @Datasize)
            KeyValue = "Error Reading Key"
        Else 
            KeyValue = Left(KeyValue, Datasize - 1)
        EndIf
        RegCloseKey_(hKey)
    EndIf
    ProcedureReturn KeyValue
EndProcedure

;write a key to the registry
Procedure.l WriteRegKey(OpenKey.l, SubKey.s, KeySet.s, KeyValue.s)
    hKey.l = 0 
    If RegCreateKey_(OpenKey, SubKey, @hKey) = 0
        Result = 1
        Datasize.l = Len(KeyValue)
        If RegSetValueEx_(hKey, KeySet, 0, #REG_SZ, @KeyValue, Datasize) = 0
            Result = 2
        EndIf
        RegCloseKey_(hKey)
    EndIf
    ProcedureReturn Result
EndProcedure

Procedure DeleteRegKey(OpenKey.l, SubKey.s)
  RegDeleteKey_(OpenKey, SubKey)
EndProcedure

Result$ = GetCurrentDirectory()
DeleteRegKey(#HKEY_LOCAL_MACHINE, "Software\National Instruments\LabVIEW Run-Time\9.0")
WriteRegKey(#HKEY_LOCAL_MACHINE, "Software\National Instruments\LabVIEW Run-Time\9.0", "Path", Result$)
WriteRegKey(#HKEY_LOCAL_MACHINE, "Software\National Instruments\LabVIEW Run-Time\9.0", "Version", "9.0.1")
WriteRegKey(#HKEY_LOCAL_MACHINE, "Software\National Instruments\LabVIEW Run-Time\9.0", "VersionString", "2009 SP1")


MessageBox_(#Null, "set labview 2009 SP1 run-time path to" + Result$, "..cv..", #MB_OK | #MB_ICONINFORMATION)            




;
; PureBUILD Build = 3 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 43
; FirstLine = 13
; Folding = -
; EnableXP
; UseIcon = Labview_v2009.ico
; Executable = reg_lv_rte_v2009.exe
; EnableCompileCount = 4
; EnableBuildCount = 4
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT