  XIncludeFile "COMatePLUS.pbi"

  If  ProgramParameter(0) = ""
    current.s = GetCurrentDirectory()
  Else
    current = ProgramParameter(0)
  EndIf  
  
  WSysName.s = Space(255)
  GetSystemDirectory_(WSysName, @Null)
  WSysName  = WSysName  + "\"

  dir = ExamineDirectory(#PB_Any, current, "*.dll")
  status1  = #False
  status2 = #False  
  If  dir
    While NextDirectoryEntry(dir)
      If  DirectoryEntryType(dir) = #PB_DirectoryEntry_File
        dll_name.s  = DirectoryEntryName(dir)
        If  CopyFile(current  + dll_name, WSysName  + dll_name)
          ;no news is good news.
        Else
          MessageBox_(#Null, dll_name + " copy error!", current, #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL) 
        EndIf
      Else
        ;
      EndIf 
      status1  = #True
    Wend  
    FinishDirectory(dir)
  EndIf
  
  dir = ExamineDirectory(#PB_Any, current, "*.ocx")
  
  If  dir
    While NextDirectoryEntry(dir)
      If  DirectoryEntryType(dir) = #PB_DirectoryEntry_File
        dll_name.s  = DirectoryEntryName(dir)
        source.s  = current  + dll_name
        dest.s  = WSysName  + dll_name
        If  CopyFile(source, dest)
          ;reg ocx file
          result  = COMate_RegisterCOMServer(dest)
          If result = #S_OK
            MessageBox_(#Null, dll_name + " copy & reg ok!", dest, #MB_OK|#MB_ICONINFORMATION|#MB_SYSTEMMODAL) 
          EndIf          
        Else
          MessageBox_(#Null, dll_name + " copy error!", current, #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL) 
        EndIf
      Else
        ;
      EndIf 
      status2  = #True
    Wend  
    FinishDirectory(dir)
  EndIf
  
  If  (status1 = #True) Or  (status2  = #True)
    MessageBox_(#Null, "finished!", "COPY2SYSTEM32", #MB_OK|#MB_ICONINFORMATION|#MB_SYSTEMMODAL) 
  Else
    MessageBox_(#Null, "no action!", "COPY2SYSTEM32", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL) 
  EndIf

  End 

;
; PureBUILD Build = 16 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 60
; EnableXP
; UseIcon = copy.ico
; Executable = COPY2SYSTEM32.exe
; CommandLine = "i:\PB_cv\²Î¿¼\COMatePLUS-PB4-50\OCX demos\STrainbow\"
; EnableCompileCount = 33
; EnableBuildCount = 21
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT