  ;10/12/2012 09:25:10
  IncludePath "BIN"
  XIncludeFile "COMatePLUS.pbi"  
  
  If  ProgramParameter(0) = ""
    MessageBox_(#Null, "no parameter!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
    StandardFile.s = "example.lbx"
    Pattern.s = "lbx (*.lbx)|*.lbx|All files (*.*)|*.*"
    lbx_file_path.s = OpenFileRequester("Please choose lbx file to load", StandardFile, Pattern, 0)
    
    If lbx_file_path
      ;
    Else
      MessageBox_(#Null, "no file selected!!!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
      End
    EndIf
  Else
    Select  FileSize(ProgramParameter(0))
      Case  -1
        MessageBox_(#Null, "file is not exist!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
        End
      Case  -2
        MessageBox_(#Null, "please do not use folder!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
        End
      Default
        If  "lbx" = GetExtensionPart(ProgramParameter(0))
          lbx_file_path  = ProgramParameter(0)
        Else
          MessageBox_(#Null, "lbx file only!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
          End          
        EndIf
    EndSelect    
  EndIf    
  
  
  Define  brother.COMateObject
  Define.s  pri_text, num_of
  
  brother = COMate_CreateObject("bpac.Document")
  
  brother\Invoke("Open('" + lbx_file_path + "')")
  
  
  hwnd  = OpenWindow(#PB_Any, 0, 0, 450, 60, "cv pb example", #PB_Window_MinimizeGadget|#PB_Window_ScreenCentered|#PB_Window_SystemMenu)
  SetWindowPos_(WindowID(hWnd), #HWND_TOP, 0, 0, 0, 0, #SWP_NOMOVE|#SWP_NOSIZE) 
  SmartWindowRefresh(hwnd, 1) 
  StickyWindow(hwnd, #True)
  SetWindowTitle(hwnd, lbx_file_path)
    
  print_bg = ButtonGadget(#PB_Any, 300, 20, 60, 20, "¥Ú”°", #PB_Button_Default)
  GadgetToolTip(print_bg, "")
  label_sg  = StringGadget(#PB_Any, 10, 20, 120, 20, "Label")
  GadgetToolTip(label_sg, "")
  num_sg  = StringGadget(#PB_Any, 140, 20, 60, 20, "1", #PB_String_Numeric)
  GadgetToolTip(num_sg, "")
  
  AddKeyboardShortcut(hwnd, #PB_Shortcut_Escape, 0)    
  AddWindowTimer(hwnd, 0, 100)
    
  Repeat
    Event.l = WaitWindowEvent()
    Select  Event
      Case  #PB_Event_Timer
        Select  EventTimer()
          Case  0
            ;
        EndSelect
      Case  #PB_Event_Gadget
        Select  EventGadget()
          Case  print_bg            
            pri_text  = GetGadgetText(label_sg)
            num_of  = GetGadgetText(num_sg)
            brother\Invoke("SetText(0, '" + pri_text + "')")            
            brother\Invoke("DoPrint(1, 'MyDoc, " + num_of + "')")       
        EndSelect
      Case  #PB_Event_Menu
        Select EventMenu()
          Case  0
            quit  = #True
        EndSelect
    EndSelect
  Until Event = #PB_Event_CloseWindow Or  quit  = #True
     
  brother\Invoke("close()")
  brother\Release()
  CloseWindow(hwnd)    
  End     
  
  
  
  
  
  
  DataSection
    
  ; file_start1:
  ;   IncludeBinary ""
  ; file_end1:
  
  EndDataSection
  
  
  
  
  
  


;
; PureBUILD Build = 7 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 43
; FirstLine = 25
; EnableThread
; EnableXP
; UseIcon = BIN\PT18R.ico
; Executable = Release\BROTHER_HELPER.exe
; CompileSourceDirectory
; EnableCompileCount = 33
; EnableBuildCount = 8
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = %EXECUTABLE@%OS
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv
; VersionField18 = CCCC
; VersionField19 = cv
; VersionField20 = cuiwei
; VersionField21 = cccc
; VersionField22 = 2012
; VersionField23 = cuiwei