IncludePath  "BIN"

Procedure.s ReadRegKey(OpenKey.l, SubKey.s, ValueName.s)
    hKey.l = 0
    KeyValue.s = Space(255)
    Datasize.l = 255
    If RegOpenKeyEx_(OpenKey, SubKey, 0, #KEY_READ, @hKey)
        KeyValue = "Error Opening Key"
    Else
        If RegQueryValueEx_(hKey, ValueName, 0, 0, @KeyValue, @Datasize)
            KeyValue = "Error Reading Key"
        Else 
            KeyValue = Left(KeyValue, Datasize - 1)
        EndIf
        RegCloseKey_(hKey)
    EndIf
    ProcedureReturn KeyValue
EndProcedure

Procedure release_file()
  
  temp.s = GetTemporaryDirectory()
;-------------------------------------------------
  file1_name.s  = temp  + "MFC71.dll"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart1, ?fileend1 - ?filestart1)
    CloseFile(file1)
  EndIf
;--------------------------------------------------
  file1_name.s  = temp  + "MSVCP71.DLL"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart2, ?fileend2 - ?filestart2)
    CloseFile(file1)
  EndIf  
;--------------------------------------------------
  file1_name.s  = temp  + "msvcr71.dll"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart3, ?fileend3 - ?filestart3)
    CloseFile(file1)
  EndIf    
  
;--------------------------------------------------
  file1_name.s  = temp  + "Pxiswiz.chm"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart4, ?fileend4 - ?filestart4)
    CloseFile(file1)
  EndIf 
  
;--------------------------------------------------
  file1_name.s  = temp  + "pxiswiz.exe"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart5, ?fileend5 - ?filestart5)
    CloseFile(file1)
  EndIf 
EndProcedure

Procedure delete_file()
  
  temp.s = GetTemporaryDirectory()
  
  DeleteFile(temp  + "MFC71.dll")
  DeleteFile(temp  + "MSVCP71.DLL")
  DeleteFile(temp  + "msvcr71.dll")
  DeleteFile(temp  + "Pxiswiz.chm")
  DeleteFile(temp  + "pxiswiz.exe")
  
EndProcedure

  If  ProgramParameter(0) = ""
    parameter.s = ""
  Else
    parameter = ProgramParameter(0)
  EndIf

  release_file()

  temp.s = GetTemporaryDirectory()
  
  name.s  = Chr(34) + temp + "pxiswiz.exe"  + Chr(34)
  
  version.s = ReadRegKey(#HKEY_LOCAL_MACHINE, "SOFTWARE\National Instruments\NI-VISA for Windows 95/NT\CurrentVersion", "Version")
  
  If  version <> "3.3.1"
    If  version = "Error Opening Key"
      MessageBox_(#Null, "请先安装ni-visa v3.3.1 runtime", "..cv..", #MB_OK | #MB_ICONINFORMATION)
	    End
    Else
      MessageBox_(#Null, "当前ni-visa版本为v"	+	version	+	Chr(10) + "推荐使用 ni-visa v3.3.1", "..cv..", #MB_OK | #MB_ICONINFORMATION)
    EndIf  
  Else
    ;
  EndIf
  
  If  parameter = ""
    Pattern$ = "ni-visa驱动模板 (*.ini)|*.ini|All files (*.*)|*.*"
    file2.s = OpenFileRequester("Please choose file to open", "", Pattern$, #PB_Window_WindowCentered)
    If  file2 = ""
      MessageBox_(#Null, "no file selected!" + Chr(10) + "use Default!", "..cv..", #MB_OK | #MB_ICONINFORMATION)
      result = RunProgram(name, "", temp, #PB_Program_Wait)
    Else
      result = RunProgram(name, file2, temp, #PB_Program_Wait)
    EndIf
  Else
    result = RunProgram(name, parameter, temp, #PB_Program_Wait)
  EndIf  
  
  delete_file()
  
  End

  DataSection
    
    filestart1: 
      IncludeBinary "MFC71.dll" 
    fileend1: 
      
    filestart2: 
      IncludeBinary "MSVCP71.DLL" 
    fileend2: 
      
    filestart3: 
      IncludeBinary "msvcr71.dll" 
    fileend3: 
      
    filestart4: 
      IncludeBinary "Pxiswiz.chm" 
    fileend4: 
      
    filestart5: 
      IncludeBinary "pxiswiz.exe" 
    fileend5: 
    
  EndDataSection  

;
; PureBUILD Build = 15 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 115
; FirstLine = 98
; Folding = -
; EnableXP
; UseIcon = NI-VISA.ico
; Executable = Release\VISA_PXI_DRIVER_GENERATOR.exe
; EnableCompileCount = 36
; EnableBuildCount = 15
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv