IncludePath  "BIN"

Procedure.s ReadRegKey(OpenKey.l, SubKey.s, ValueName.s)
    hKey.l = 0
    KeyValue.s = Space(255)
    Datasize.l = 255
    If RegOpenKeyEx_(OpenKey, SubKey, 0, #KEY_READ, @hKey)
        KeyValue = "Error Opening Key"
    Else
        If RegQueryValueEx_(hKey, ValueName, 0, 0, @KeyValue, @Datasize)
            KeyValue = "Error Reading Key"
        Else 
            KeyValue = Left(KeyValue, Datasize - 1)
        EndIf
        RegCloseKey_(hKey)
    EndIf
    ProcedureReturn KeyValue
EndProcedure

Procedure release_file()
  
  temp.s = GetTemporaryDirectory()
;-------------------------------------------------
  file1_name.s  = temp  + "viic_ext.dll"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart1, ?fileend1 - ?filestart1)
    CloseFile(file1)
  EndIf
;--------------------------------------------------
  file1_name.s  = temp  + "NIvisaic.exe"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart2, ?fileend2 - ?filestart2)
    CloseFile(file1)
  EndIf  
;--------------------------------------------------
  file1_name.s  = temp  + "NIvisaic.hlp"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart3, ?fileend3 - ?filestart3)
    CloseFile(file1)
  EndIf    
  
;--------------------------------------------------
  file1_name.s  = temp  + "visaic.ini"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart4, ?fileend4 - ?filestart4)
    CloseFile(file1)
  EndIf 
  
;--------------------------------------------------
  file1_name.s  = temp  + "visastat.ini"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart5, ?fileend5 - ?filestart5)
    CloseFile(file1)
  EndIf 
  
;--------------------------------------------------
  file1_name.s  = temp  + "Visaic.uir"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart6, ?fileend6 - ?filestart6)
    CloseFile(file1)
  EndIf 
  
;--------------------------------------------------
  file1_name.s  = temp  + "Visaio.uir"
  result.q = FileSize(file1_name)
  If  result > 0
    ;
  Else
    file1 = CreateFile(#PB_Any, file1_name)
    WriteData(file1, ?filestart7, ?fileend7 - ?filestart7)
    CloseFile(file1)
  EndIf 
EndProcedure

Procedure delete_file()
  
  temp.s = GetTemporaryDirectory()
  
  DeleteFile(temp  + "viic_ext.dll")
  DeleteFile(temp  + "NIvisaic.exe")
  DeleteFile(temp  + "NIvisaic.hlp")
  DeleteFile(temp  + "visaic.ini")
  DeleteFile(temp  + "visastat.ini")
  DeleteFile(temp  + "Visaic.uir")
  DeleteFile(temp  + "Visaio.uir")  
  
EndProcedure

  If  ProgramParameter(0) = ""
    parameter.s = ""
  Else
    parameter = ProgramParameter(0)
  EndIf

  release_file()

  temp.s = GetTemporaryDirectory()
  
  name.s  = Chr(34) + temp + "NIvisaic.exe"  + Chr(34)
  
  version.s = ReadRegKey(#HKEY_LOCAL_MACHINE, "SOFTWARE\National Instruments\NI-VISA for Windows 95/NT\CurrentVersion", "Version")
  
  If  version <> "3.3.1"
    If  version = "Error Opening Key"
      MessageBox_(#Null, "请先安装ni-visa v3.3.1 runtime", "..cv..", #MB_OK | #MB_ICONINFORMATION)
	    End
    Else
      MessageBox_(#Null, "当前ni-visa版本为v"	+	version	+	Chr(10) + "推荐使用 ni-visa v3.3.1", "..cv..", #MB_OK | #MB_ICONINFORMATION)
    EndIf  
  Else
    ;
  EndIf
  
  result = RunProgram(name, "", temp, #PB_Program_Wait) 
  
  delete_file()
  
  End

  DataSection
    
    filestart1: 
      IncludeBinary "viic_ext.dll" 
    fileend1: 
      
    filestart2: 
      IncludeBinary "NIvisaic.exe" 
    fileend2: 
      
    filestart3: 
      IncludeBinary "NIvisaic.hlp" 
    fileend3: 
      
    filestart4: 
      IncludeBinary "visaic.ini" 
    fileend4: 
      
    filestart5: 
      IncludeBinary "visastat.ini" 
    fileend5: 
      
    filestart6: 
      IncludeBinary "Visaic.uir" 
    fileend6: 
      
    filestart7: 
      IncludeBinary "Visaio.uir" 
    fileend7: 
    
  EndDataSection  

;
; PureBUILD Build = 19 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 122
; FirstLine = 113
; Folding = -
; EnableXP
; UseIcon = NIvisaic_new.ico
; Executable = Release\NIvisaic_cv.exe
; EnableCompileCount = 40
; EnableBuildCount = 19
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv