  IncludePath "Include\"
  icon = CatchImage(#PB_Any, ?icon_tester)
  
  hWnd  = OpenWindow(#PB_Any, 0, 0, 540, 235, "cvPXILib_PB_tester", #PB_Window_SystemMenu | #PB_Window_ScreenCentered)
  SetWindowPos_(hWnd, #HWND_TOP, 0, 0, 0, 0, #SWP_NOMOVE|#SWP_NOSIZE)
  
  
  CB_hWnd = ComboBoxGadget(#PB_Any, 10, 10, 330, 25, #PB_ComboBox_Image | #PB_ComboBox_Editable)
  
  AddGadgetItem(CB_hWnd, -1, "select_card_pb", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "visa_find_rsrc_ex", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "select_plx9054_card", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "get_fifo_status_pb", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "bar_and_offset", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "About", ImageID(icon))
  AddGadgetItem(CB_hWnd, -1, "find_available_serial", ImageID(icon))
  SetGadgetState(CB_hWnd, 0)     
  
  button1 = ButtonGadget(#PB_Any, 20, 200, 90, 25, "RUN", #PB_Button_Default)
  GadgetToolTip(button1, "RUN")
  
  dll = OpenLibrary(#PB_Any, "cvPXILib_PB.dll")

  Repeat
    Event.l = WaitWindowEvent()
    Select  Event
      Case  #PB_Event_Gadget
        Select  EventGadget()
          Case  button1
            Result.l = GetGadgetState(CB_hWnd)
            Select  GetGadgetItemText(CB_hWnd, Result)
              Case  "select_card_pb"
                CallFunction(dll, "select_card_pb")
              Case  "select_plx9054_card"
                CallFunction(dll, "select_plx9054_card")
              Case  "About"
                CallFunction(dll, "About")
              Case  "get_fifo_status_pb"
                CallFunction(dll, "get_fifo_status_pb")
              Case  "visa_find_rsrc_ex"
                *result3 = AllocateMemory(3000) 
                CallFunction(dll, "visa_find_rsrc_ex", *result3)
                FreeMemory(*result3)
              Case  "bar_and_offset"
                *result2 = AllocateMemory(3000) 
                CallFunction(dll, "bar_and_offset", *result2)
                FreeMemory(*result2)  
              Case  "find_available_serial"
                *result4 = AllocateMemory(3000) 
                CallFunction(dll, "find_available_serial", *result4)
                FreeMemory(*result4)  
            EndSelect            
        EndSelect
      Case  #PB_Event_Menu
        Select EventMenu()
          Case  button1
            quit  = #True
        EndSelect 
    EndSelect
  Until Event = #PB_Event_CloseWindow Or  quit  = #True    

  CloseLibrary(dll)
  End
  
  DataSection
    icon_tester  : 
    IncludeBinary "Icon\tester.ico"
  EndDataSection




;
; PureBUILD Build = 12 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.50 (Windows - x86)
; CursorPosition = 49
; FirstLine = 22
; EnableXP
; UseIcon = Include\Icon\tester.ico
; Executable = Release\cvPXILib_PB_tester.exe
; EnableCompileCount = 17
; EnableBuildCount = 3
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1.0
