;- Image Plugins
UsePNGImageDecoder()
;-------------------------------------------------------------
Declare   About()
;-------------------------------------------------------------
IncludePath "Include\"                ;file included
IncludeFile "select_card_pb.pb"       ;
IncludeFile "get_fifo_status_pb.pb"   ;
IncludeFile "visa_find_rsrc_ex.pb"    ;
IncludeFile "interrupt_checker_pb.pb" ;
IncludeFile "select_plx9054_card.pb"  ;
IncludeFile "count_cvPXILib_functions.pb" ;
IncludeFile "About.pb" ;
IncludeFile "bar_and_offset.pb" ;
IncludeFile "find_available_serial.pb";
;-------------------------------------------------------------
Procedure AttachProcess(Instance)
EndProcedure
;-------------------------------------------------------------
Procedure AttachThread(Instance)
EndProcedure
;-------------------------------------------------------------
Procedure DetachThread(Instance)
EndProcedure
;-------------------------------------------------------------
Procedure DetachProcess(Instance)
EndProcedure
;-------------------------------------------------------------
DataSection
  Icon_close:
  IncludeBinary "Icon\close.png"
  Icon_next:
  IncludeBinary "Icon\next.png"
  Icon_card1:
  IncludeBinary "Icon\card1.ico"
  Icon_card2:
  IncludeBinary "Icon\card2.ico"
  Icon_card3:
  IncludeBinary "Icon\card3.ico"
  Icon_card4:
  IncludeBinary "Icon\card4.ico"
  Icon_card5:
  IncludeBinary "Icon\card5.ico"
  Icon_card6:
  IncludeBinary "Icon\card6.ico"
  Icon_card7:
  IncludeBinary "Icon\card7.ico"
  Icon_card8:
  IncludeBinary "Icon\card8.ico"
  Icon_card9:
  IncludeBinary "Icon\card9.ico"
  Icon_xilinx:
  IncludeBinary "Icon\xilinx.ico"
  Icon_PlxIcon:
  IncludeBinary "Icon\PlxIcon.ico"
  Icon_opencore:
  IncludeBinary "Icon\opencore.ico"
  Icon_visa32:
  IncludeBinary "Icon\NI-VISA_icon2.ico"
  Icon_lxi:
  IncludeBinary "Icon\LXI.ico"
  AboutSoundFile:
  IncludeBinary "Music\PCO.MOD"
  Icon_bar:
  IncludeBinary "Icon\bar.ico"
  bird1:
  IncludeBinary "Images\bird_01.png"
  bird2:
  IncludeBinary "Images\bird_02.png"
  bird3:
  IncludeBinary "Images\bird_03.png"
  icon_rs232:
  IncludeBinary "Icon\rs232.ico"
EndDataSection





;
; PureBUILD Build = 12 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.50 (Windows - x86)
; ExecutableFormat = Shared Dll
; CursorPosition = 71
; FirstLine = 51
; Folding = -
; EnableXP
; Executable = Release\cvPXILib_PB.dll
; EnableCompileCount = 114
; EnableBuildCount = 104
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1.0.0.1
; VersionField1 = 1.0.0.1
; VersionField2 = kt
; VersionField3 = cvPXILib
; VersionField4 = 1.0.0.1
; VersionField6 = cvPXILib_PB
; VersionField13 = cuiwei_cv@163.com
