  ;10/11/2012 14:41:51
  IncludePath "BIN"
  
  Structure NEW_LUID_AND_ATTRIBUTES
     pLuid.LUID
     Attributes.l
  EndStructure
   
  Structure NEW_TOKEN_PRIVILEGES
    PrivilegeCount.l
    Privileges.NEW_LUID_AND_ATTRIBUTES[#ANYSIZE_ARRAY]
  EndStructure  
  
  Procedure.b DitchWindows(flags)
    Protected os.OSVERSIONINFO:os\dwOSVersionInfoSize=SizeOf(OSVERSIONINFO)
    GetVersionEx_(os)
    If os\dwPlatformId=#VER_PLATFORM_WIN32_NT
      If OpenProcessToken_(GetCurrentProcess_(),#TOKEN_ADJUST_PRIVILEGES|#TOKEN_QUERY,@token)
        If LookupPrivilegeValue_(#Null,"SeShutdownPrivilege",tkp.NEW_TOKEN_PRIVILEGES\Privileges[0]\pLuid)
          tkp\PrivilegeCount=1
          tkp\Privileges[0]\Attributes=#SE_PRIVILEGE_ENABLED
          If AdjustTokenPrivileges_(token,#False,tkp,#Null,#Null,#Null)
            If ExitWindowsEx_(flags,0)=0:ProcedureReturn 4:EndIf
          Else:ProcedureReturn 3
          EndIf
        Else:ProcedureReturn 2
        EndIf
      Else:ProcedureReturn 1
      EndIf
    Else
      If ExitWindowsEx_(flags,0)=0
        ProcedureReturn 4
      EndIf
    EndIf
  EndProcedure  
  
  Procedure.b Reboot(force=0)
    If force:force=#EWX_FORCE:EndIf
    DitchWindows(#EWX_LOGOFF|#EWX_REBOOT|force)
  EndProcedure  
  
  process_id = RunProgram("setup.exe", "/q /r", GetPathPart(ProgramFilename()), #PB_Program_Open)
  
  If  0 <>  process_id
    ;
  Else
    MessageBox_(#Null, "error!", "..cv..", #MB_ICONERROR|#MB_SYSTEMMODAL)
    End
  EndIf
  
  Repeat
    Delay(500)
    If  0 = ProgramRunning(process_id)
      result  = MessageBox_(#Null, "visa32 setup complete!" + Chr(10) + "reboot this computer?", "..cv..", #MB_YESNO|#MB_ICONQUESTION|#MB_SYSTEMMODAL|#MB_DEFBUTTON2)
      Select  result
        Case  #IDYES
          Reboot()
          End
        Case  #IDNO
          ;
      EndSelect
      Break      
    EndIf    
  ForEver  
  
  End  
  
  


;
; PureBUILD Build = 8 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 57
; FirstLine = 2
; Folding = -
; EnableXP
; EnableAdmin
; UseIcon = BIN\NI-VISA.ico
; Executable = Release\visa_setup_helper.exe
; CompileSourceDirectory
; EnableCompileCount = 8
; EnableBuildCount = 8
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv
; VersionField18 = CCCC
; VersionField19 = cv
; VersionField20 = cuiwei
; VersionField21 = cccc
; VersionField22 = 2012
; VersionField23 = cuiwei