
  XIncludeFile "COMatePLUS.pbi"

  Structure conn_pack
    name.s{1024}
    count.s{1024}
  EndStructure
  
  NewList total_data.conn_pack()
  
  Define.COMateObject ExcelObject, WorkBook
  ExcelObject = COMate_CreateObject("Excel.Application")
    
  ExcelObject\SetProperty("Visible = #false")
  current_path.s  = GetPathPart(ProgramFilename())
  WorkBook = ExcelObject\GetObjectProperty("Workbooks\Open('" + current_path  + "input.xls')")
  
  For x=1 To  2500 Step  1
    AddElement(total_data())
    total_data()\name = ExcelObject\GetStringProperty("Cells(" + Str(x) + ",1)")
    total_data()\count  = ExcelObject\GetStringProperty("Cells(" + Str(x) + ",4)")
  Next  x
      
  ExcelObject\Invoke("Quit()")
  WorkBook\Release()
  ExcelObject\Release() 
  
  UseSQLiteDatabase()
  NewList connector_name.s()
  
  If OpenFile(0, GetPathPart(ProgramFilename()) + "output_list.txt")   
    While Eof(0) = 0         
      AddElement(connector_name())
      connector_name() = ReadString(0, #PB_Ascii) 
    Wend
    CloseFile(0)
  EndIf

  Filename$ = GetPathPart(ProgramFilename()) + "cv.sqlite"
  
  If CreateFile(0, Filename$)
    Debug "Database file created"
    CloseFile(0)
  EndIf
  
  If OpenDatabase(0, Filename$, "", "", #PB_Database_SQLite)
    
    Debug "Connected to cv.sqlite"
    If DatabaseUpdate(0, "CREATE TABLE connector_info (connector VARCHAR(255), count VARCHAR(255));")
      Debug "Table created"
    EndIf

    ForEach connector_name()
      ForEach total_data()
        If  total_data()\name = connector_name()
          DatabaseUpdate(0, "INSERT INTO connector_info VALUES ('" + connector_name() + "', '" + total_data()\count + "')")    
        EndIf  
      Next
    Next
    
  EndIf
  
  CloseDatabase(0)
  
  MessageBox_(GetFocus_(), "finished!", "-=cv=- 2013.2", #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
  
  FreeList(connector_name())
  FreeList(total_data())
  End

;
; PureBUILD Build = 11 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 38
; FirstLine = 9
; EnableUnicode
; UseIcon = ck.ico
; Executable = connector_check_pro_cv.exe
; CompileSourceDirectory
; EnableCompileCount = 17
; EnableBuildCount = 10
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv