
  XIncludeFile "COMatePLUS.pbi"

  Procedure.q GetConnectorCount(input_name.s)
    Define.COMateObject ExcelObject, WorkBook
    ExcelObject = COMate_CreateObject("Excel.Application")
    
    ExcelObject\SetProperty("Visible = #false")
    current_path.s  = GetCurrentDirectory()
    WorkBook = ExcelObject\GetObjectProperty("Workbooks\Open('" + current_path  + "input.xls')")
    
    For x=1 To  1000 Step  1
      name$ = ExcelObject\GetStringProperty("Cells(" + Str(x) + ",1)")
      count$ = ExcelObject\GetStringProperty("Cells(" + Str(x) + ",4)")
      If  name$  = input_name
        Break
      EndIf
    Next  x
    
    ExcelObject\Invoke("Quit()")
    WorkBook\Release()
    ExcelObject\Release() 
    
    ProcedureReturn  Val(count$)
   
  EndProcedure

  UseSQLiteDatabase()
  NewList connector_name.s()
  
  If OpenFile(0, "output_list.txt")   
    While Eof(0) = 0         
      AddElement(connector_name())
      connector_name() = ReadString(0, #PB_Ascii) 
    Wend
    CloseFile(0)
  EndIf



  Filename$ = GetCurrentDirectory() + "cv.sqlite"
  
  If CreateFile(0, Filename$)
    Debug "Database file created"
    CloseFile(0)
  EndIf
  
  If OpenDatabase(0, Filename$, "", "", #PB_Database_SQLite)
    
    Debug "Connected to cv.sqlite"
    If DatabaseUpdate(0, "CREATE TABLE connector_info (connector VARCHAR(255), count VARCHAR(255));")
      Debug "Table created"
    EndIf

    ForEach connector_name()
      Debug connector_name() + ":" + Str(GetConnectorCount(connector_name()))
      DatabaseUpdate(0, "INSERT INTO connector_info VALUES ('" + connector_name() + "', '" + Str(GetConnectorCount(connector_name())) + "')")    
    Next
    
  EndIf
  
  CloseDatabase(0)
  
  MessageBox_(GetFocus_(), "finished!", "-=cv=- 2013.2", #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
  
  End

;
; PureBUILD Build = 7 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 63
; FirstLine = 33
; Folding = -
; EnableUnicode
; Executable = connector_check_cv.exe
; CompileSourceDirectory
; EnableCompileCount = 7
; EnableBuildCount = 6
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv