OpenConsole()
ConsoleTitle("ping -=cv=-")

ConsoleColor(10, 0)

PrintN("«Î ‰»ÎIPµÿ÷∑£∫")

aaaa.s = Input()


Ping = RunProgram("Ping", aaaa  + " -n 100", "", #PB_Program_Open)

aaaa.s = Input()

CloseConsole()






;
; PureBUILD Build = 4 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 10
; EnableXP
; UseIcon = ping.ico
; Executable = Release\ping_cv.exe
; EnableCompileCount = 4
; EnableBuildCount = 4
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv