OpenConsole()
show_interface  = RunProgram("netsh.exe", "interface ip show config", "", #PB_Program_Open | #PB_Program_Wait)
Delay(2500)
ClearConsole()
PrintN("请输入新IP地址<本地连接>：")

aaaa.s = Input()


name.s  = Chr(34) + "本地连接"  + Chr(34)
If  aaaa  <>  ""
  set_ip = RunProgram("netsh.exe", "interface ip set address name=" +name+ " static " + aaaa + " 255.255.255.0", "", #PB_Program_Open | #PB_Program_Hide | #PB_Program_Wait)
  MessageBox_(GetFocus_(), "New IP set ok: " + aaaa, "..cv..", #MB_OK | #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
Else
  MessageBox_(GetFocus_(), "请输入正确IP地址", "..cv..", #MB_OK | #MB_ICONERROR|#MB_SYSTEMMODAL)  
EndIf

End

;
; PureBUILD Build = 10 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 18
; EnableXP
; UseIcon = set_ip.ico
; Executable = Release\set_ip_cv.exe
; EnableCompileCount = 18
; EnableBuildCount = 9
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv