IncludePath "BIN"

If  ProgramParameter(0) = ""
  parameter.s = ""
Else
  parameter = ProgramParameter(0);
EndIf

current.s = Space(255)
GetModuleFileName_(0, current, #MAX_PATH)
;current.s = GetCurrentDirectory()

Debug current
current = GetPathPart(current)

Debug current

lic.s = current + "cadence_v15.5.lic"

Debug lic
lm_license_file.s = PeekS(?filestart1, ?fileend1  - ?filestart1, #PB_Ascii)
DeleteFile(lic)
license_file  = CreateFile(#PB_Any, lic)
WriteString(license_file, lm_license_file, #PB_Ascii)
CloseFile(license_file)


SetEnvironmentVariable("CDS_LIC_FILE", lic)
SetEnvironmentVariable("CDS_LIC_ONLY", "1")


;MessageBox_(#Null, "环境变量设置完成！", "..cv..", #MB_OK | #MB_ICONINFORMATION)

name.s  = current + "Capture.exe"
parameter = Chr(34) + parameter + Chr(34)
;MessageBox_(#Null, parameter, "..cv..", #MB_OK | #MB_ICONINFORMATION)
result = RunProgram(name, parameter, current, #PB_Program_Wait)

DeleteFile(lic)
End


DataSection
    
  filestart1: 
    IncludeBinary "cadence_v15.5.lic" 
  fileend1:     
  
EndDataSection



;
; PureBUILD Build = 21 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.11 (Windows - x86)
; CursorPosition = 38
; FirstLine = 1
; EnableXP
; UseIcon = BIN\Capture_cv.ico
; Executable = ..\Capture_loader.exe
; CommandLine = "ccc.dsn"
; CompileSourceDirectory
; EnableCompileCount = 44
; EnableBuildCount = 23
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv