  IncludePath "BIN"

  Procedure.s ReadRegKey(OpenKey.l, SubKey.s, ValueName.s)
      hKey.l = 0
      KeyValue.s = Space(255)
      Datasize.l = 255
      If RegOpenKeyEx_(OpenKey, SubKey, 0, #KEY_READ, @hKey)
          KeyValue = "Error Opening Key"
      Else
          If RegQueryValueEx_(hKey, ValueName, 0, 0, @KeyValue, @Datasize)
              KeyValue = "Error Reading Key"
          Else 
              KeyValue = Left(KeyValue, Datasize - 1)
          EndIf
          RegCloseKey_(hKey)
      EndIf
      ProcedureReturn KeyValue
  EndProcedure
  
  
  If  ProgramParameter(0) = ""
    current_path.s = PathRequester("Please choose your path", "C:\")
    If current_path
      ;
    Else
      MessageBox_(#Null, "empty path selected!!!", "-=cv=- 2012.6", #MB_ICONERROR|#MB_SYSTEMMODAL)
      End
    EndIf
  Else
    Select  FileSize(ProgramParameter(0))
      Case  -1          ;File not found
        End
      Case  -2          ;File is a directory
        current_path  = ProgramParameter(0)
      Default
        End
    EndSelect
  EndIf  
  
  winrar_path.s  = ReadRegKey(#HKEY_LOCAL_MACHINE, "Software\Winrar", "exe32") 
  
  If  winrar_path = "Error Opening Key"
    MessageBox_(#Null, "no winrar found!!!", "-=cv=- 2012.6", #MB_ICONERROR|#MB_SYSTEMMODAL)
    End
  Else
    ;
  EndIf
  
  count = CountString(current_path, "\")
  
  father_path.s = RemoveString(current_path, StringField(current_path, count, "\") + "\", 0, 1, 1)
  
  rar_pack_name.s = father_path + StringField(current_path, count, "\") + "_cv.rar"
  
  parameter.s = " a  -s -t -m5  -ag[yyyyMMdd-HHmmss] -x*.bak " + Chr(34) + rar_pack_name + Chr(34) + " " + Chr(34) + StringField(current_path, count, "\") + Chr(34)
  
  result  = RunProgram(winrar_path, parameter, father_path, #PB_Program_Wait|#PB_Program_Hide)
  
  If  result
    MessageBox_(#Null, "finished!" + Chr(13) + "save to " + father_path, "-=cv=- 2012.6", #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
  Else
    MessageBox_(#Null, "no run!", "-=cv=- 2012.6", #MB_ICONERROR|#MB_SYSTEMMODAL)
  EndIf
  
  
  End  
  
  
  
  
  
  
  DataSection
    
  ; file_start1:
  ;   IncludeBinary ""
  ; file_end1:
  
  EndDataSection
  
  
  
  
  
  


;
; PureBUILD Build = 14 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 26
; Folding = -
; EnableXP
; UseIcon = BIN\WinRAR.ico
; Executable = Release\PROJECT_FILES_PACKER.exe
; CompileSourceDirectory
; EnableCompileCount = 33
; EnableBuildCount = 14
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv
; VersionField18 = CCCC
; VersionField19 = cv
; VersionField20 = cuiwei
; VersionField21 = cccc
; VersionField22 = 2012
; VersionField23 = cuiwei