  IncludePath  "BIN"
  
  MessageBox_(GetFocus_(), ProgramParameter(0), "cv", #MB_OK)
  


;
; PureBUILD Build = 56 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.11 (Windows - x86)
; CursorPosition = 7
; Markers = 3
; EnableAsm
; EnableThread
; EnableXP
; UseIcon = print.ico
; Executable = Release\print_parameter.exe
; CommandLine = cccc
; EnableCompileCount = 314
; EnableBuildCount = 57
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = hex editor
; VersionField8 = hex