
  If  ProgramParameter(0) = ""
    current.s = GetCurrentDirectory()
  Else
    current = ProgramParameter(0)
  EndIf
  
  OutputDebugString_(ProgramParameter(0))
  
  count.q = 0
  
  dir = ExamineDirectory(#PB_Any, current, "*.exe")
  If  NextDirectoryEntry(dir)
    DeleteFile(current  + "md5_check.md5")
    file  = CreateFile(#PB_Any, current + "md5_check.md5")
  Else
    ;
  EndIf
  FinishDirectory(dir)
     
  dir = ExamineDirectory(#PB_Any, current, "*.exe")
  If  dir
    While NextDirectoryEntry(dir)
      If  DirectoryEntryType(dir) = #PB_DirectoryEntry_File
        exe_name.s  = DirectoryEntryName(dir)
        exe_md5.s = MD5FileFingerprint(current + exe_name)
        WriteStringN(file, exe_md5  + " " + exe_name)   
        count = count + 1
      Else
        ;
      EndIf 
    Wend  
    FinishDirectory(dir)
  EndIf
  
  If  count
    CloseFile(file)
    MessageBox_(#Null, "md5 build ok!", current, #MB_ICONINFORMATION|#MB_SYSTEMMODAL)
  Else
    MessageBox_(#Null, "no *.exe file founded!", current, #MB_ICONERROR|#MB_SYSTEMMODAL)
  EndIf
  
  End
  
  
  


;
; PureBUILD Build = 8 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 37
; FirstLine = 2
; EnableXP
; UseIcon = md5.ico
; Executable = exe_md5_maker.exe
; EnableCompileCount = 14
; EnableBuildCount = 14
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT