del /s /q *.ncb
del /s /q *.res
del /s /q *.plg
del /s /q *.aps
del /s /q AppLog.txt
del /s /q DebugData.txt
del /s /q *.idb
del /s /q *.ilk
del /s /q *.obj
del /s /q *.pch
del /s /q *.positions
del /s /q *.sbr
del /s /q *.chw
rd /s /q html
rd /s /q rtf
del /s /q *.bsc