IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

load_wrapper_dll()

card_select.s = Space(4096)

Dim card_array.card_info(2)

If  ProgramParameter(0) = ""
  id_num.s  = "*"
  result  = select_visa_pci_pxi_card(@card_select, @id_num)  
Else
  card_select =  ProgramParameter(0)
EndIf  

result  = is_plx9054_exist(@card_select)

If  result  = #False
  End
EndIf

visa_default.q  = 0
viOpenDefaultRM(@visa_default)
    
card_res.q  = 0
viOpen(visa_default, @card_select, #VI_NO_LOCK, 1000, @card_res)

result  = get_plx9054_fpga_logic_version(card_res)
MessageBox_(#Null, "fpga_logic_version for this card is " + Str(result), "..cv..", #MB_OK | #MB_ICONINFORMATION|#MB_SYSTEMMODAL)

viClose(card_res)
viClose(visa_default)

close_wrapper_dll()

End








;
; PureBUILD Build = 18 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 3
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\get_fpga_logic_version.exe
; CompileSourceDirectory
; EnableCompileCount = 53
; EnableBuildCount = 17
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv