IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

PureValid_CheckFile("cccc")

load_wrapper_dll()

card_select.s{4096} = Space(4096)

Dim card_array.card_info(2)

If  ProgramParameter(0) = ""
  result  = select_visa_pci_pxi_card(@card_select)  
  If  result  = #False
    close_wrapper_dll()
    End
  EndIf  
Else
  card_select =  ProgramParameter(0)
EndIf

result  = is_plx9054_exist(@card_select)

If  result  = #False
  End
EndIf

visa_default.q  = 0
viOpenDefaultRM(@visa_default)
    
card_res.q  = 0
viOpen(visa_default, @card_select, #VI_NO_LOCK, 1000, @card_res)

result  = check_plx9054_eeprom_is_cv_style(card_res)

Define  test_data.l = 0

If  result <> #True
  plx9054_read_eeprom_32(card_res, $44, @test_data)
  hex_input(@test_data, 32)
  burn_cv_style_eeprom_for_this_plx9054(card_res, test_data)
Else
  MessageBox_(#Null, "is cv_style_eeprom already!", "..cv..", #MB_OK|#MB_ICONINFORMATION|#MB_SYSTEMMODAL)
EndIf

viClose(card_res)
viClose(visa_default)

close_wrapper_dll()

End








;
; PureBUILD Build = 17 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 40
; EnableThread
; EnableXP
; UseIcon = new_icon\eeprom.ico
; Executable = Release\goto_cv_style_eeprom.exe
; SubSystem = UserLibThreadSafe
; CompileSourceDirectory
; EnableCompileCount = 61
; EnableBuildCount = 22
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv