IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

PureValid_CheckFile("cccc")

load_wrapper_dll()

card_select.s = Space(4096)

If  ProgramParameter(0) = ""
  result  = select_visa_usb_device(@card_select, $0957, $173D)  
Else
  card_select =  ProgramParameter(0)
EndIf  

If  result
  ;
Else
  close_wrapper_dll()
  End
EndIf

logo.s  = "Agilent MSO7034B"
splash_launcher(@logo)

MSO7034B_controlpanel(@card_select)

close_wrapper_dll()

End








;
; PureBUILD Build = 34 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 3
; EnableThread
; EnableXP
; UseIcon = new_icon\MSO7034B.ico
; Executable = Release\MSO7034B_controlpanel.exe
; SubSystem = UserLibThreadSafe
; CommandLine = USB0::0x0957::0x173D::MY50340152::INSTR
; CompileSourceDirectory
; EnableCompileCount = 166
; EnableBuildCount = 37
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv