IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

PureValid_CheckFile("cccc")  

logo.s  = "pci_usb_pnp"
splash_launcher(@logo)

load_wrapper_dll()

pci_usb_pnp_list()

close_wrapper_dll()

End








;
; PureBUILD Build = 28 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 4
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\pci_usb_pnp_list.exe
; SubSystem = UserLibThreadSafe
; CompileSourceDirectory
; EnableCompileCount = 110
; EnableBuildCount = 27
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv