IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

visa32_check_setup()
ExamineDesktops()

load_wrapper_dll()
card_select.s = Space(4096)

Dim card_array.card_info(2)

If  ProgramParameter(0) = ""
  id_num.s  = "*"
  result  = select_visa_pci_pxi_card(@card_select, @id_num)  
Else
  card_select =  ProgramParameter(0)
EndIf  

result  = is_plx9054_exist(@card_select)

If  result  = #False
  End
EndIf

logo.s  = "PCI CFG SPACE"
splash_launcher(@logo)

ori_x = (DesktopWidth(0)  - 560)/2
ori_y = (DesktopHeight(0) -  320)/2

card_array.card_info(0)\card  = @card_select
card_array.card_info(0)\x  = ori_x
card_array.card_info(0)\y  = ori_y  - 90

thread1  = CreateThread(@plx9054_reset_card_ex(), @card_array())

card_array.card_info(1)\card  = @card_select
card_array.card_info(1)\bar  = #VI_PXI_CFG_SPACE
card_array.card_info(1)\offset_address  = $0
card_array.card_info(1)\x  = ori_x
card_array.card_info(1)\y  = ori_y
card_array.card_info(1)\title  = @"PCI CONFIG SPACE"
card_array.card_info(1)\backup1  = $54

pxi_block_access(@card_array() + SizeOf(card_info))

close_wrapper_dll()

End








;
; PureBUILD Build = 114 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 6
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\PCI_CFG_viewer.exe
; CompileSourceDirectory
; EnableCompileCount = 177
; EnableBuildCount = 105
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv