IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

PureValid_CheckFile("cccc")  

visa_check_setup()
ExamineDesktops()
load_wrapper_dll()
card_select.s = Space(4096)

Dim card_array.card_info(2)
Define  ram0_selector.l = 0

If  ProgramParameter(0) = ""
  result  = select_visa_pci_pxi_card(@card_select)  
  If  result  = #False
    close_wrapper_dll()
    End
  EndIf  
Else
  card_select =  ProgramParameter(0)
EndIf  

If  ProgramParameter(1) = ""
  result  = select_ram0(@ram0_selector)
  If  result  = #False
    close_wrapper_dll()
    End
  EndIf  
Else
  ram0_selector =  Val(ProgramParameter(1))
EndIf  

result  = is_plx9054_exist(@card_select)

If  result  = #False
  close_wrapper_dll()
  End
EndIf

logo.s  = "PLX9054 RAM0_" + Str(ram0_selector) + " SPACE"
splash_launcher(@logo)

ori_x = (DesktopWidth(0)  - 560)/2
ori_y = (DesktopHeight(0) -  320)/2

title.s = "ram0_" + Str(ram0_selector) + "@bar2: 0x" + Hex($400*ram0_selector, #PB_Long) + "~0x" + Hex($400*ram0_selector + $3ff, #PB_Long)

card_array.card_info(1)\card  = @card_select
card_array.card_info(1)\bar  = #VI_PXI_BAR2_SPACE
card_array.card_info(1)\offset_address  = $400*ram0_selector
card_array.card_info(1)\x  = ori_x
card_array.card_info(1)\y  = ori_y
card_array.card_info(1)\title  = @title
card_array.card_info(1)\backup1  = $400

pxi_block_access(@card_array() + SizeOf(card_info))

close_wrapper_dll()

End








;
; PureBUILD Build = 132 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 11
; EnableThread
; EnableXP
; UseIcon = new_icon\ram0.ico
; Executable = Release\plx9054_ram0_viewer.exe
; SubSystem = UserLibThreadSafe
; CompileSourceDirectory
; EnableCompileCount = 271
; EnableBuildCount = 135
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv