IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

visa32_check_setup()

load_wrapper_dll()

card_select.s = Space(4096)

If  ProgramParameter(0) = ""
  id_num.s  = "*"
  result  = select_visa_pci_pxi_card(@card_select, @id_num)  
Else
  card_select =  ProgramParameter(0)
EndIf  

result  = is_plx9054_exist(@card_select)

If  result  = #False
  close_wrapper_dll()
  End
EndIf

logo.s  = "PLX9054 DMA SPY"
splash_launcher(@logo)

plx9054_dma_spy(@card_select)

close_wrapper_dll()

End





























;
; PureBUILD Build = 178 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 27
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\plx9054_dma_spy.exe
; CompileSourceDirectory
; EnableCompileCount = 670
; EnableBuildCount = 169
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv