IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

Dim card_array.card_info(16)
card_select.s{4096} = Space(4096)
bar.l = 0
offset.l  = 0
x_p.l = 20
y_p.l = 20
title.s{1024} = "title"
mode.l  = 1
help.s{4096}  = ""
size.l  = 0

help  = help  + "/? for help"  + Chr(10)
help  = help  + "p0 for card"  + Chr(10)
help  = help  + "p1 for bar"  + Chr(10)
help  = help  + "p2 for offset"  + Chr(10)
help  = help  + "p3 for x"  + Chr(10)
help  = help  + "p4 for y"  + Chr(10)
help  = help  + "p5 for title"  + Chr(10)
help  = help  + "p6 for mode"  + Chr(10)
help  = help  + "[p7 for size]"  + Chr(10)

load_wrapper_dll()

p0.s  = ProgramParameter()
Select  p0
  Case  ""
    id_num.s  = "*"
    result  = select_visa_pci_pxi_card(@card_select, @id_num)
    If  result  <>  #True
      close_wrapper_dll()
      End
    EndIf    
  Case  "/?"
    MessageBox_(GetFocus_(), @help, "cv", #MB_SYSTEMMODAL)
    close_wrapper_dll()
    End    
  Default
    card_select = p0
EndSelect

p1.s  = ProgramParameter()
If  p1 = ""
  result  = select_bar(@bar)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  bar =  Val(p1)
EndIf

p2.s  = ProgramParameter()
If  p2 = ""
  result  = Hex_input(@offset, 32)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  offset =  Val(ReplaceString(p2, "0x", "$", #PB_String_NoCase, 1))
EndIf

p3.s  = ProgramParameter()
If  p3 = ""
  result  = Dec_input(@x_p)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  x_p =  Val(p3)
EndIf

p4.s  = ProgramParameter()
If  p4 = ""
  result  = Dec_input(@y_p)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  y_p =  Val(p4)
EndIf

p5.s  = ProgramParameter()
If  p5 = ""
  result  = String_input(@title)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  title =  p5
EndIf

p6.s  = ProgramParameter()
If  p6 = ""
  result  = Dec_input(@mode)
  If  result  <>  #True
    close_wrapper_dll()
    End
  EndIf
Else
  mode =  Val(p6)
EndIf

If  3 = mode
  p7.s  = ProgramParameter()
  If  p7 = ""
    result  = Hex_input(@size, 32)
    If  result  <>  #True
      close_wrapper_dll()
      End
    EndIf
  Else
    size =  Val(ReplaceString(p7, "0x", "$", #PB_String_NoCase, 1))
  EndIf
EndIf

logo.s  = "register and bit"
splash_launcher(@logo)

card_array.card_info(0)\card  = @card_select
card_array.card_info(0)\bar  = bar
card_array.card_info(0)\offset_address  = offset
card_array.card_info(0)\x  = x_p
card_array.card_info(0)\y  = y_p
card_array.card_info(0)\title  = @title
card_array.card_info(0)\backup1  = size

Select  mode
  Case  0    
    MessageBox_(GetFocus_(), "mode 0 is not complete. ", "cv", #MB_SYSTEMMODAL)
  Case  1
    thread1 = CreateThread(@pxi_register_access(), @card_array()  + 0*SizeOf(card_info))        
  Case  2
    thread1 = CreateThread(@pxi_bit_access(), @card_array()  + 0*SizeOf(card_info))
  Case  3
    thread1 = CreateThread(@pxi_block_access(), @card_array() + 0*SizeOf(card_info))
EndSelect

If  IsThread(thread1)  
  WaitThread(thread1)
EndIf

close_wrapper_dll()

End








;
; PureBUILD Build = 19 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 135
; FirstLine = 119
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\register_and_bit_access.exe
; CommandLine = visa://192.168.1.2/PXI0::CHASSIS1::SLOT1::INSTR 13 0x110 100 100 ÖÐ¹ú 1
; CompileSourceDirectory
; EnableCompileCount = 91
; EnableBuildCount = 18
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv