IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

PureValid_CheckFile("cccc")
load_wrapper_dll()

card_select.s = Space(4096)
Define  test_data.l = 0
Define  hipart.w  = 0
Define  lowpart.w = 0

Dim card_array.card_info(2)

If  ProgramParameter(0) = ""
  id_num.s  = "*"
  result  = select_visa_pci_pxi_card(@card_select, @id_num)  
Else
  card_select =  ProgramParameter(0)
EndIf  

result  = is_plx9054_exist(@card_select)

If  result  = #False
  End
EndIf

logo.s  = "save_plx9054_to_eeprom_file"
splash_launcher(@logo)

visa_default.q  = 0
viOpenDefaultRM(@visa_default)
    
card_res.q  = 0
viOpen(visa_default, @card_select, #VI_NO_LOCK, 1000, @card_res)

res_name.s = Space(4096)
viGetAttribute(card_res, #VI_ATTR_RSRC_NAME, @res_name)

plx9054_read_eeprom_32(card_res, $44, @test_data)

new_file_name.s = GetPathPart(ProgramFilename()) + RemoveString(RemoveString(RemoveString(res_name, "::"), ":"), "/") + "_x" + RSet(Hex(test_data), 8, "0") + "_" + FormatDate("[%yyyy%mm%dd-%hh%ii%ss]", Date()) + ".bin" 
result  = FileSize(new_file_name) 
Select  result
  Case  -1
    ;
  Case  -2
    MessageBox_(#Null, new_file_name + " is dir!", "..cv..", #MB_ICONERROR|#MB_SYSTEMMODAL)
    viClose(card_res)
    viClose(visa_default)
    close_wrapper_dll()        
    End    
  Default
    result2 = MessageBox_(#Null, new_file_name + " is already exist! yes to rewrite, no to escape. ", "..cv..", #MB_YESNO|#MB_ICONQUESTION|#MB_SYSTEMMODAL)
    Select  result2
      Case  #IDYES
        DeleteFile(new_file_name)
      Case  #IDNO
        viClose(card_res)
        viClose(visa_default)
        close_wrapper_dll()        
        End
    EndSelect 
EndSelect

CreateFile(0, new_file_name)

For i=0 To  $54 Step 4  
  plx9054_read_eeprom_32(card_res, i, @test_data)
  lowpart = test_data
  hipart  = test_data>>16
  WriteWord(0, hipart)  
  WriteWord(0, lowpart)
Next i

CloseFile(0)        

MessageBox_(#Null, res_name + " eeprom file is save to " + new_file_name, "..cv..", #MB_OK | #MB_ICONINFORMATION|#MB_SYSTEMMODAL)

viClose(card_res)
viClose(visa_default)
close_wrapper_dll()

End








;
; PureBUILD Build = 30 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 40
; FirstLine = 11
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\save_to_eeprom_file.exe
; SubSystem = UserLibThreadSafe
; CompileSourceDirectory
; EnableCompileCount = 66
; EnableBuildCount = 28
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv