IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

load_wrapper_dll()

Define  txt_path.s{1024}  = ""
Define  help.s{1024}  = ""

p0.s  = ProgramParameter()
Select  p0
  Case  ""
    MessageBox_(GetFocus_(), "no parameter!", "-=cv=- 2012.6", #MB_OK|#MB_ICONERROR|#MB_SYSTEMMODAL)
    MessageBox_(GetFocus_(), "p0: txt file only. ", "cv", #MB_SYSTEMMODAL)    
    StandardFile.s = "test.txt"
    Pattern.s = "txt (*.txt)|*.txt|All files (*.*)|*.*"
    txt_path = OpenFileRequester("Please choose txt file to load", StandardFile, Pattern, 0)
  Case  "/?"
    help  = "p0: txt file only. "
    MessageBox_(GetFocus_(), @help, "cv", #MB_SYSTEMMODAL)
    close_wrapper_dll()
    End    
  Default
    txt_path = p0
EndSelect

Select  FileSize(txt_path)
  Case  -1
    help  = txt_path + " is not found. "
    MessageBox_(GetFocus_(), @help, "cv", #MB_SYSTEMMODAL|#MB_ICONERROR)
    close_wrapper_dll()
    End        
  Case  -2
    help  = txt_path + " is folder. "
    MessageBox_(GetFocus_(), @help, "cv", #MB_SYSTEMMODAL|#MB_ICONERROR)
    close_wrapper_dll()
    End        
  Default
    If  "txt" = GetExtensionPart(txt_path)
      ;
    Else
      help  = txt_path + " is not txt file. "
      MessageBox_(GetFocus_(), @help, "cv", #MB_SYSTEMMODAL|#MB_ICONERROR)
      close_wrapper_dll()
      End          
    EndIf    
EndSelect

file1 = ReadFile(#PB_Any, txt_path)
If file1 
  While Eof(file1) = 0
    RunProgram("register_and_bit_access.exe", ReadString(file1), GetPathPart(ProgramFilename()))
  Wend
  CloseFile(file1) 
Else
  ;
EndIf

close_wrapper_dll()

End








;
; PureBUILD Build = 22 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 11
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\testbench_from_txt.exe
; CommandLine = i:\VC++6_cv\cvPXISDK\cvPXIRunTime\cvPXIRunTime\RUN-TIMES\NI-VISA\VISA32_PB_WRAPPER\EXE_OUT\test_register_and_bit_access.txt
; CompileSourceDirectory
; EnableCompileCount = 86
; EnableBuildCount = 21
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv