IncludePath "BIN"
XIncludeFile "VISA32_PB_WRAPPER.pbi"

logo.s  = "just a test demo!"
splash_launcher(@logo)

load_wrapper_dll()

resource.s{256} = Space(256)
result  = select_visa_device(@resource)

If  result
  Debug resource
EndIf

result  = select_visa_serialport(@resource)

If  result
  Debug resource
EndIf

Debug Hex(dword_change_endian($12345678))

close_wrapper_dll()

End








;
; PureBUILD Build = 17 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 21
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\get_fpga_logic_version.exe
; CompileSourceDirectory
; EnableCompileCount = 131
; EnableBuildCount = 16
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv