  IncludePath "BIN"
  XIncludeFile "VISA32_PB_WRAPPER.pbi"
  
  PureValid_CheckFile("cccc")  
  
  Dim pc.pc_info(99) ;最多控制100台主机
  Dim thread_list.q(99)
  Dim ip_list.s{512}(99)
  
  load_wrapper_dll()  
  
  logo.s  = "VISA32 Server cv"
  splash_launcher(@logo)
    
  ip_icon  = 0
  ip_small_icon = 0
  ExtractIconEx_("cv_icons.dll", 92, @ip_icon, @ip_small_icon, 1)
  reset_icon  = 0
  ExtractIconEx_("cv_icons.dll", 45, @reset_icon, #Null, 1)  
  
  Port = 6889 
  Buffer = AllocateMemory(1024) 
  NewList server_list.s()
  server_udp  = CreateNetworkServer(#PB_Any, Port, #PB_Network_UDP)
  
  hwnd  = OpenWindow(#PB_Any, 50, 50, 20, 40, "visa_server_remote", #PB_Window_Normal)
  SetWindowPos_(WindowID(hwnd), #HWND_TOPMOST, 0, 0, 0, 0, #SWP_NOMOVE|#SWP_NOSIZE)
  SendMessage_(WindowID(hwnd), #WM_SETICON, #False, ip_small_icon) 
  SmartWindowRefresh(hwnd, 1) 
  
  exit_bg = ButtonImageGadget(#PB_Any, 0, 0, 40, 40, ip_icon)
  reset_bg = ButtonImageGadget(#PB_Any, 40, 0, 40, 40, reset_icon)
  
  GadgetToolTip(exit_bg, "exit")
  GadgetToolTip(reset_bg, "刷新")

  AddWindowTimer(hwnd, 0, 5)
  AddWindowTimer(hwnd, 1, 10000) ;10s的timeout
  AddWindowTimer(hwnd, 2, 1000)
  
  i = 0
  Repeat
    Event.l = WaitWindowEvent()
    Select  Event
      Case  #PB_Event_Timer
        Select  EventTimer()
          Case  0
            SEvent = NetworkServerEvent() 
            If SEvent
              ClientID = EventClient()
              ClientIP$ = IPString(GetClientIP(ClientID))
              aa  = 1;unique flag
              
              Select SEvent 
                Case 2        
                  ForEach server_list()   
                    If  ClientIP$ = server_list()
                      aa  = 0
                      Break
                    Else
                      aa  = 1    
                    EndIf
                  Next
                  
                  If  aa =  1          
                    AddElement(server_list())          
                    server_list() = ClientIP$
                    ip_list(i)  = ClientIP$
                    With  pc(i)
                      \x  = 100 + 20*i
                      \y  = 100 + 20*i
                      \ip_address_pt  = @ip_list(i)
                    EndWith
                    thread_list(i)  = CreateThread(@visa_server_remote(), @pc(i))
                    If  i < 99
                      i = i + 1
                    Else
                      i = 0
                    EndIf
                  Else
                    ;
                  EndIf
                  
              EndSelect
            EndIf
          Case  1
            If  ListSize(server_list()) = 0
              result  = MessageBox_(GetFocus_(), "no server find, exit?", "..cv..", #MB_YESNO | #MB_ICONQUESTION|#MB_SYSTEMMODAL)
              Select  result
                Case  6 ;yes
                  quit  = #True
                Case  7 ;no
                  ;
                Default
                  ;
              EndSelect
            Else
              ;
            EndIf
          Case  2
            ;
        EndSelect
      Case  #PB_Event_Gadget
        Select  EventGadget()
          Case  exit_bg
            quit  = #True
          Case  reset_bg
            i = 0
            ClearList(server_list())
            For k=0 To 99 Step  1
              If  0 <>  thread_list(k)
                If  0 = WaitThread(thread_list(k), 100)
                  KillThread(thread_list(k))
                  thread_list(k)  = 0
                EndIf
              EndIf
            Next
        EndSelect
      Case  #PB_Event_Menu
        Select EventMenu()
          Case  0
            ;
        EndSelect
    EndSelect
  Until Event = #PB_Event_CloseWindow Or  quit  = #True
    
  CloseWindow(hwnd)      
  CloseNetworkServer(server_udp)
  FreeList(server_list())
  FreeMemory(Buffer)
  close_wrapper_dll()
  
  End
  
  






;
; PureBUILD Build = 68 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 5.00 (Windows - x86)
; CursorPosition = 87
; FirstLine = 72
; EnableThread
; EnableXP
; UseIcon = BIN\cv.ico
; Executable = Release\visa_server_remote.exe
; SubSystem = UserLibThreadSafe
; DisableDebugger
; CompileSourceDirectory
; EnableCompileCount = 264
; EnableBuildCount = 66
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv