IncludePath "BIN"

If  ProgramParameter(0) = ""
  parameter.s = ""
Else
  parameter = ProgramParameter(0)
EndIf


current.s = GetCurrentDirectory()

path.s = current + "bin"

If  FindString(GetEnvironmentVariable("PATH"), "Debussy", 1)
  ;
Else
  parameter2.s ="PATH " + Chr(34) + GetEnvironmentVariable("PATH") + ";" + path + Chr(34)
EndIf  
  
temp_folder.s = GetTemporaryDirectory()

file1_name.s  = temp_folder + "setx.exe"

result.q = FileSize(file1_name)
If  result > 0
  ;
Else
  file1 = CreateFile(#PB_Any, file1_name)
  WriteData(file1, ?filestart1, ?fileend1 - ?filestart1)
  CloseFile(file1)
EndIf   

result = RunProgram(file1_name, parameter2, temp_folder, #PB_Program_Wait | #PB_Program_Hide)


If  result
  ;
Else
  MessageBox_(#Null, "error!" + Chr(10) + parameter, "..cv..", #MB_OK | #MB_ICONERROR)
EndIf

DeleteFile(file1_name)

path.s = GetEnvironmentVariable("PATH") + ";" + current + "bin"

SetEnvironmentVariable("PATH", path)

name.s  = current + "bin\Debussy.exe"

result = RunProgram(name, parameter, current, #PB_Program_Wait)


End

DataSection
    
  filestart1: 
    IncludeBinary "setx.exe" 
  fileend1:     
  
EndDataSection


;
; PureBUILD Build = 19 [generated by PureBUILD Plugin]
; IDE Options = PureBasic 4.60 (Windows - x86)
; CursorPosition = 17
; EnableXP
; UseIcon = BIN\Debussy_cv.ico
; Executable = ..\Debussy_loader.exe
; CompileSourceDirectory
; EnableCompileCount = 24
; EnableBuildCount = 18
; EnableExeConstant
; IncludeVersionInfo
; VersionField0 = 1,0,0,%BUILDCOUNT
; VersionField1 = 1,0,0,%BUILDCOUNT
; VersionField2 = cv
; VersionField3 = cv
; VersionField4 = 1,0,0,%BUILDCOUNT
; VersionField5 = 1,0,0,%BUILDCOUNT
; VersionField6 = cv
; VersionField7 = cv
; VersionField8 = cv